// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlxEouFuVojNBROdskaMYYAYZngPGVPRU',
    appId: '1:366322664983:web:9a7b200f2d76f7557fbe52',
    messagingSenderId: '366322664983',
    projectId: 'projectr-2c416',
    authDomain: 'projectr-2c416.firebaseapp.com',
    storageBucket: 'projectr-2c416.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUBcU1crEDJ6i3IoqAuzNpSSb8By_qRCw',
    appId: '1:366322664983:android:fd3d2f8facc183407fbe52',
    messagingSenderId: '366322664983',
    projectId: 'projectr-2c416',
    storageBucket: 'projectr-2c416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7j40pA5eNY8PxqfO7ZrpxhCUFsAmmb-A',
    appId: '1:366322664983:ios:27b8357f1f8c5eb67fbe52',
    messagingSenderId: '366322664983',
    projectId: 'projectr-2c416',
    storageBucket: 'projectr-2c416.firebasestorage.app',
    iosClientId: '366322664983-r4smog5eclb7g0ueq9bcbsia82vt0di3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7j40pA5eNY8PxqfO7ZrpxhCUFsAmmb-A',
    appId: '1:366322664983:ios:27b8357f1f8c5eb67fbe52',
    messagingSenderId: '366322664983',
    projectId: 'projectr-2c416',
    storageBucket: 'projectr-2c416.firebasestorage.app',
    iosClientId: '366322664983-r4smog5eclb7g0ueq9bcbsia82vt0di3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlxEouFuVojNBROdskaMYYAYZngPGVPRU',
    appId: '1:366322664983:web:f5ba1485358473c97fbe52',
    messagingSenderId: '366322664983',
    projectId: 'projectr-2c416',
    authDomain: 'projectr-2c416.firebaseapp.com',
    storageBucket: 'projectr-2c416.firebasestorage.app',
  );
}
